#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES: connect a Supabase project to Agent School.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=6
ENV_FILE=".env.local"
REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$REPO_ROOT"

# copy_clip TEXT puts TEXT on the clipboard so the human can paste it straight
# into a browser field. Does nothing where no clipboard tool exists.
copy_clip() {
  if   command -v pbcopy   >/dev/null 2>&1; then printf '%s' "$1" | pbcopy
  elif command -v xclip    >/dev/null 2>&1; then printf '%s' "$1" | xclip -selection clipboard
  elif command -v clip.exe >/dev/null 2>&1; then printf '%s' "$1" | clip.exe
  else return 1; fi
  printf '  %s✓ copied to clipboard%s\n' "$GREEN" "$RESET"
}

copy_file_clip() {
  if   command -v pbcopy   >/dev/null 2>&1; then pbcopy < "$1"
  elif command -v xclip    >/dev/null 2>&1; then xclip -selection clipboard < "$1"
  elif command -v clip.exe >/dev/null 2>&1; then clip.exe < "$1"
  else return 1; fi
  printf '  %s✓ copied %s to clipboard%s\n' "$GREEN" "$1" "$RESET"
}

banner "Agent School · Supabase setup"

# ── 1 ─────────────────────────────────────────────────────────────────────
stage "Supabase: project URL and publishable key"
say "These two values are all the app needs to talk to your project."
open_url "https://supabase.com/dashboard/project/_/settings/api"
step "Settings → API. Copy the value under 'Project URL'."
note "It looks like https://abcdefghijklm.supabase.co"
ask NEXT_PUBLIC_SUPABASE_URL "Paste the Project URL:"
NEXT_PUBLIC_SUPABASE_URL="${NEXT_PUBLIC_SUPABASE_URL%/}"

while [[ ! "$NEXT_PUBLIC_SUPABASE_URL" =~ ^https://[a-z0-9-]+\.supabase\.co$ ]]; do
  warn "that does not look like a project URL"
  ask NEXT_PUBLIC_SUPABASE_URL "Paste the Project URL again:"
  NEXT_PUBLIC_SUPABASE_URL="${NEXT_PUBLIC_SUPABASE_URL%/}"
done

PROJECT_REF="${NEXT_PUBLIC_SUPABASE_URL#https://}"
PROJECT_REF="${PROJECT_REF%%.*}"
CALLBACK_URL="https://${PROJECT_REF}.supabase.co/auth/v1/callback"

printf '\n'
step "Now open Settings → API Keys and copy the publishable key."
open_url "https://supabase.com/dashboard/project/${PROJECT_REF}/settings/api-keys"
note "Starts with sb_publishable_. The older 'anon public' JWT also works."
note "Never paste the secret or service_role key; this one ships to browsers."
ask NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY "Paste the publishable key:"

while [[ -z "$NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY" || "$NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY" == sb_secret_* ]]; do
  warn "that is empty or a server-side key, which must never reach the browser"
  ask NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY "Paste the publishable key:"
done

write_env NEXT_PUBLIC_SUPABASE_URL "$NEXT_PUBLIC_SUPABASE_URL"
write_env NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY "$NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY"
write_env NEXT_PUBLIC_SITE_URL "http://localhost:3000"
pause "Done. Enter for the next stage."

# ── 2 ─────────────────────────────────────────────────────────────────────
stage "Supabase: create the tables"
say "supabase/schema.sql creates four tables, their row-level security"
say "policies, and the two triggers that mirror new users and hide reported"
say "projects. Running it twice is safe."
copy_file_clip "supabase/schema.sql" || note "copy supabase/schema.sql by hand"
open_url "https://supabase.com/dashboard/project/${PROJECT_REF}/sql/new"
step "Paste into the SQL editor (already on your clipboard)."
step "Press Run, or Cmd+Enter."
step "You want 'Success. No rows returned' at the bottom."
warn "If it says type project_status already exists, you have run it before"
note "  and everything is fine. Carry on."
pause "Ran it? Enter to continue."

# ── 3 ─────────────────────────────────────────────────────────────────────
stage "Supabase: allow redirects back to localhost"
say "Supabase refuses to send a user anywhere that is not on this allowlist,"
say "which is the most common reason sign-in silently fails."
open_url "https://supabase.com/dashboard/project/${PROJECT_REF}/auth/url-configuration"
step "Set 'Site URL' to exactly:  http://localhost:3000"
step "Under 'Redirect URLs', click Add URL and enter:  http://localhost:3000/**"
note "The double asterisk matters. The app returns to /auth/callback?next=..."
note "and a single asterisk will not match a query string."
step "Save."
pause "Saved? Enter to continue."

# ── 4 ─────────────────────────────────────────────────────────────────────
stage "GitHub sign-in"
say "Two tabs: create an OAuth app on GitHub, then paste its credentials"
say "into Supabase."
printf '\n'
step "GitHub asks for an 'Authorization callback URL'. It is NOT localhost."
step "It is your Supabase project:"
printf '\n      %s%s%s\n\n' "$BOLD" "$CALLBACK_URL" "$RESET"
copy_clip "$CALLBACK_URL" || true
open_url "https://github.com/settings/applications/new"
step "Application name: Agent School"
step "Homepage URL: http://localhost:3000"
step "Authorization callback URL: paste the URL above, it is on your clipboard"
step "Click 'Register application'."
step "Copy the Client ID, then 'Generate a new client secret' and copy that."
pause "Got both? Enter to open Supabase."

open_url "https://supabase.com/dashboard/project/${PROJECT_REF}/auth/providers"
step "Authentication → Sign In / Providers. Expand GitHub in the list."
step "Turn 'Enable Sign in with GitHub' on."
step "Paste the Client ID and Client Secret. Save."
pause "Saved? Enter to continue."

# ── 5 ─────────────────────────────────────────────────────────────────────
stage "Google sign-in"
say "Same shape as GitHub, with one extra step: Google makes you fill in a"
say "consent screen before it will hand out a client ID."
open_url "https://console.cloud.google.com/auth/overview"
step "If prompted, create a project, then complete 'Branding' and 'Audience'."
step "While testing, set publishing status to Testing and add your own Google"
note "  account under 'Test users', or sign-in will be blocked."
pause "Consent screen done? Enter to create the client."

open_url "https://console.cloud.google.com/auth/clients/create"
step "Application type: Web application"
step "Authorized JavaScript origins, Add URI:  http://localhost:3000"
step "Authorized redirect URIs, Add URI:"
printf '\n      %s%s%s\n\n' "$BOLD" "$CALLBACK_URL" "$RESET"
copy_clip "$CALLBACK_URL" || true
step "Create, then copy the Client ID and Client Secret."
pause "Got both? Enter to open Supabase."

open_url "https://supabase.com/dashboard/project/${PROJECT_REF}/auth/providers"
step "Expand Google. Turn 'Enable Sign in with Google' on."
step "Paste the Client ID and Client Secret. Save."
pause "Saved? Enter to verify everything."

# ── 6 ─────────────────────────────────────────────────────────────────────
stage "Verify"
say "Starting the app and asking it what it can see."

STARTED_DEV=0
if curl -fsS -m 3 "http://localhost:3000/api/health" >/dev/null 2>&1; then
  note "using the dev server already running on :3000"
  note "if the check below says the keys are missing, restart that server"
else
  note "starting npm run dev, output in /tmp/agent-school-dev.log"
  npm run dev >/tmp/agent-school-dev.log 2>&1 &
  STARTED_DEV=$!
fi

HEALTH=""
for _ in $(seq 1 45); do
  HEALTH=$(curl -fsS -m 3 "http://localhost:3000/api/health" 2>/dev/null || true)
  [[ -n "$HEALTH" ]] && break
  sleep 1
done

if [[ -z "$HEALTH" ]]; then
  warn "the dev server never answered; check /tmp/agent-school-dev.log"
  SKIPPED+=("verification: dev server did not start")
else
  printf '\n'
  printf '%s' "$HEALTH" | node -e '
    let raw = "";
    process.stdin.on("data", (d) => (raw += d));
    process.stdin.on("end", () => {
      const E = String.fromCharCode(27);
      const G = E + "[32m", R = E + "[31m", X = E + "[0m";
      const ok = (s) => console.log("  " + G + "✓" + X + " " + s);
      const no = (s) => console.log("  " + R + "✗" + X + " " + s);
      let h;
      try { h = JSON.parse(raw); } catch { return no("health endpoint returned nothing usable"); }
      if (!h.configured) return no("keys not picked up: " + h.hint);
      ok("connected to project " + h.projectRef);
      for (const [table, state] of Object.entries(h.tables)) {
        state === "ok" ? ok("table " + table) : no("table " + table + ": " + state);
      }
      h.schemaReady
        ? ok("schema is complete")
        : no("schema incomplete, re-run supabase/schema.sql from stage 2");
    });
  ' || warn "could not read the health response"
fi

printf '\n'
say "The last check is one only you can do:"
open_url "http://localhost:3000/community"
step "Click Sign in, choose GitHub, approve."
step "You should land back on /community with your handle in the header."
step "Then submit a project and reload. If it survives the reload it is in"
note "  Postgres and the wall is live."
pause "Try it, then press Enter."

if confirm "Did sign-in and the project submission both work?"; then
  printf '\n'
  say "Then you are done."
else
  SKIPPED+=("sign-in or submission failed, see the notes printed above")
  printf '\n'
  warn "Most likely causes, in order:"
  note "  1. Redirect URLs missing http://localhost:3000/** (stage 3)"
  note "  2. Provider callback URL is not $CALLBACK_URL (stages 4, 5)"
  note "  3. Your Google account is not in 'Test users' (stage 5)"
  note "  4. Schema not run, so the profiles trigger never fired (stage 2)"
  note "  Server errors are logged to /tmp/agent-school-dev.log"
fi

if [[ "$STARTED_DEV" != "0" ]]; then
  pkill -P "$STARTED_DEV" 2>/dev/null || true
  kill "$STARTED_DEV" 2>/dev/null || true
  note "stopped the dev server this script started; run npm run dev yourself"
fi

finish
